spring:
  application:
    name: n-bang-api

  datasource:
    url: jdbc:postgresql://localhost:5432/nbang
    driver-class-name: org.postgresql.Driver
    username: nbang
    password: nbang

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  docker:
    compose:
      enabled: true
      lifecycle-management: start-and-stop

server:
  port: 8080